apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-preferred
  namespace: sched-$STUDENT_NAME
spec:
  containers:
  - name: app
    image: nginx:1.25-alpine
    resources:
      requests: { cpu: 50m, memory: 32Mi }
      limits: { cpu: 100m, memory: 64Mi }
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        preference:
          matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - ${ZONE}
